# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
