# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170603_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.FileField(blank=True, default='no-img.jpg', null=True, upload_to=''),
        ),
    ]
