# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170604_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_description',
            field=models.TextField(default='', help_text='Enter a brief description of the authors', max_length=1000),
        ),
    ]
